SCENARIO_SELECTION_LENGTH = 600
HERO_SELECTION_LENGTH = 600
MAX_PLAYERS = 5
DOUBLE_MAX_PLAYERS = MAX_PLAYERS * 2
SUPER_MAX_PLAYERS = 20
CAN_PICK_FROM_OTHER_TEAM = false
START_WITH_PAUSE = true
CLIENT_PRINT = true