MAX_PLAYERS = 5
DOUBLE_MAX_PLAYERS = MAX_PLAYERS * 2
SUPER_MAX_PLAYERS = 20
CAN_PICK_FROM_OTHER_TEAM = true
SCENARIO_SELECTION_LENGTH = 600
HERO_SELECTION_LENGTH = 600
START_WITH_PAUSE = true
CLIENT_PRINT = false
ALLOW_CUSTOM_SCENARIO = true
WORKING_BOTS = true		-- BOTS are always added, this just makes them move
INCLUDED_SCENARIOS = {"n1_blck_gg", "n2_g2_liquid", "n3_comeback31k"}
DISABLE_SPECTATORS_OUTSIDE_LOBBY = false
SKIP_COMMON_NEUTRALS = true
AUTO_START = true

DEBUG = false
SLOW_TIME_FRIENDLY = false
SKIP_CREEPS = false
PRINT_DAY_NIGHT = false
TRACK_ROSHAN = false
PLAYER_LARGE_VISSIO = false

if not IsInToolsMode() then
	DEBUG = false
	SLOW_TIME_FRIENDLY = false
	PRINT_DAY_NIGHT = false
	TRACK_ROSHAN = false
	PLAYER_LARGE_VISSIO = false
	SKIP_CREEPS = false
end