MAX_PLAYERS = 5
DOUBLE_MAX_PLAYERS = MAX_PLAYERS * 2
SUPER_MAX_PLAYERS = 20
CAN_PICK_FROM_OTHER_TEAM = true
SCENARIO_SELECTION_LENGTH = 600
HERO_SELECTION_LENGTH = 600
START_WITH_PAUSE = true
CLIENT_PRINT = false
ALLOW_CUSTOM_SCENARIO = true
WORKING_BOTS = true		-- BOTS are always added, this just makes them move
INCLUDED_SCENARIOS = {"n1_dacha_group_ts_bb", "n2_dacha_group_lgd_liquid", "n3_dacha_group_liquid_vp"}
DISABLE_SPECTATORS_OUTSIDE_LOBBY = false
SKIP_COMMON_NEUTRALS = true
AUTO_START = true
BOTS_ARE_DUMMER_IN_SINGLE_PLAYER = true
SCRAMBLE_POST_GAME_SUMMARY = false

DEBUG = false
SLOW_TIME_FRIENDLY = false
SKIP_CREEPS = false
PRINT_DAY_NIGHT = false
TRACK_ROSHAN = false
PLAYER_LARGE_VISSIO = false

IS_PRO_VERSION = false

if IS_PRO_VERSION then
	WORKING_BOTS = false           -- BOTS are always added, this just makes them move
	INCLUDED_SCENARIOS = {"n3_comeback31k"}
	DISABLE_SPECTATORS_OUTSIDE_LOBBY = true
	SKIP_COMMON_NEUTRALS = false
	AUTO_START = false
	BOTS_ARE_DUMMER_IN_SINGLE_PLAYER = false
	SCRAMBLE_POST_GAME_SUMMARY = true
end


if not IsInToolsMode() then
	DEBUG = false
	SLOW_TIME_FRIENDLY = false
	PRINT_DAY_NIGHT = false
	TRACK_ROSHAN = false
	PLAYER_LARGE_VISSIO = false
	SKIP_CREEPS = false
end